version: "2"

linters:
  default: all
  disable:
    - wsl
    - wsl_v5
    - wrapcheck
    - varnamelen
    - tagliatelle
    - noinlineerr
    - nlreturn
    - nilerr
    - ireturn
    - exhaustruct
    - exhaustruct_v5
    - gomodguard
    - testpackage
    - paralleltest
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - go/ast
            - go/parser
            - go/token
            - github.com/greeddj/go-galaxy
            - github.com/Masterminds/semver/v3
            - github.com/ProtonMail/go-crypto
            - github.com/go-git/go-git/v5
            - github.com/go-git/go-billy/v5
            - golang.org/x/crypto/ssh
            - github.com/klauspost/pgzip
            - github.com/psvmcc/hub
            - github.com/urfave/cli/v3
            - go.etcd.io/bbolt
            - go.yaml.in/yaml/v3
            - github.com/BurntSushi/toml
    goconst:
      exclude-types:
        - Call
        - CompositeLit
    lll:
      line-length: 140
    musttag:
      functions:
        - name: go.yaml.in/yaml/v3.Marshal
          tag: yaml
          arg-pos: 0
        - name: go.yaml.in/yaml/v3.Unmarshal
          tag: yaml
          arg-pos: 1
    misspell:
      locale: US
  exclusions:
    generated: lax
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$

formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
