---
collections:
  - name: amarao.ip
    version: 0.1.11
  - name: ansible.posix
    version: 2.0.0
  - name: ansible.utils
    version: 6.0.0
  - name: community.crypto
    version: 3.0.1
  - name: community.general
    version: 11.1.0
  - name: community.libvirt
    version: 1.3.1
  - name: community.postgresql
    version: 4.1.0
  - name: containers.podman
    version: 1.17.0
  - name: kubernetes.core
    version: 6.2.0
  - name: serverscom.mitogen
    version: 1.4.0
  - name: t_systems_mms.acme
