package s3

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/xml"
	"fmt"
	"io"
	"maps"
	"net"
	"net/http"
	"net/http/httptest"
	"slices"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/greeddj/go-galaxy/internal/galaxy/config"
	"github.com/greeddj/go-galaxy/internal/galaxy/helpers"
)

// bucketListKey is the pseudo object key countRequest/requestCount use for a
// bucket-level ListObjectsV2 request; no real key can collide with it, since
// every real key under this fake's buckets is a slash-delimited path.
const bucketListKey = "list-objects-v2"

// bucketDeleteObjectsKey is bucketListKey's counterpart for a Multi-Object
// Delete (POST ?delete) request.
const bucketDeleteObjectsKey = "delete-objects"

// fakeObject is one stored object: its body, the X-Amz-Meta-* headers it was
// last written with (captured verbatim, keyed by canonical header name), and
// the time it was last written, which stands in for S3's Last-Modified.
type fakeObject struct {
	modified time.Time
	meta     map[string]string
	etag     string
	data     []byte
}

// fakeETag mints a distinct entity tag per stored version: unlike S3's
// MD5-of-body ETag, the sequence number gives two writes of identical bytes
// different tags, which is what a compare-and-swap test depends on.
func fakeETag(body []byte, modified time.Time, seq uint64) string {
	sum := sha256.Sum256(body)
	return fmt.Sprintf("%q", fmt.Sprintf("%x-%d-%d", sum[:8], modified.UnixNano(), seq))
}

// fakeS3 is a minimal in-memory, path-style S3 fake that drives Backend and
// Client over real HTTP round trips; it never verifies the SigV4
// Authorization header the client always sends.
type fakeS3 struct {
	objects map[string]fakeObject
	// fails is keyed like requests ("METHOD key"), plus a wildcard " key"
	// matching any method, so a test can arm independent rules for two
	// methods on the same key at once.
	fails    map[string]*forcedFailure
	requests map[string]int
	// drips is keyed by object key, armed via dripGet: a matching GET never
	// finishes its body on its own (see driveDripGet).
	drips map[string]time.Duration
	// syntheticBodies is keyed by object key, armed via serveSyntheticBody:
	// a matching GET answers with that many generated bytes instead of a
	// stored object (see handleGet).
	syntheticBodies map[string]int64
	// headTokenSwaps is keyed by object key, armed via raceTokenOnNextHead:
	// the next HEAD for that key rewrites the stored token first, as if another
	// writer's PUT landed between this call's write and its follow-up HEAD.
	headTokenSwaps map[string]string
	// listResume maps each continuation token listPage issued to the last key
	// of the page it ended, which the next page starts after.
	listResume map[string]string
	// listTokensIssued and listTokensReceived record, in order, the tokens
	// listPage issued and the token of each request it answered ("" for none);
	// a request a failNext rule or writeOversizedList answers is not recorded.
	listTokensIssued   []string
	listTokensReceived []string
	failDeleteObjects  *deleteObjectsFailure
	lastDeleteHeaders  http.Header
	bucket             string
	lastDeleteReq      deleteRequest
	deleteDelay        time.Duration
	// listPageSize caps the keys handleList returns per page, set through
	// setListPageSize; zero answers every listing in a single page.
	listPageSize int
	mu           sync.Mutex
	// etagSeq numbers stored versions so no two writes share an entity tag.
	etagSeq           uint64
	ignoreIfNoneMatch bool
	// ignoreIfMatch simulates a backend that accepts a compare-and-swap PUT
	// without enforcing it, which is what Open's capability probe must catch.
	ignoreIfMatch bool
	// refuseIfMatch simulates a backend that answers every compare-and-swap
	// with 412, matching ETag or not: a probe checking refusals alone would
	// pass it, yet no reclaim on it could ever succeed.
	refuseIfMatch bool
	// suppressETag simulates a backend that names no version on a read,
	// leaving nothing to swap against; unlike ignoreIfMatch it refuses the
	// swap honestly rather than accepting it without arbitration.
	suppressETag bool
	// listOmitNextToken makes a truncated page carry no NextContinuationToken,
	// the shape of a server that says more remain yet names no way to them.
	listOmitNextToken     bool
	oversizedList         bool
	oversizedDeleteResult bool
}

// deleteObjectsFailure makes handleDeleteObjects report key as a per-key
// <Error> while still deleting every other key in the batch: the partial
// failure a real DeleteObjects can report under an overall 200 status.
type deleteObjectsFailure struct {
	key     string
	code    string
	message string
}

// forcedFailure is a fault-injection rule matched by object key and method:
// while remaining is nonzero a matching request gets status (and body, if
// set) instead of the normal response; a negative remaining never runs out.
type forcedFailure struct {
	body      []byte // optional response body written alongside status, e.g. an S3 <Error> document
	status    int
	remaining int
}

// newFakeS3 constructs an empty fake bucket store named "test". One
// instance must be created per test so state never leaks between parallel
// tests.
func newFakeS3() *fakeS3 {
	return &fakeS3{
		objects: make(map[string]fakeObject),
		bucket:  "test",
	}
}

// ServeHTTP routes requests to the bucket root or an object path.
func (f *fakeS3) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	root := "/" + f.bucket
	switch {
	case r.URL.Path == root:
		f.handleBucket(w, r)
	case strings.HasPrefix(r.URL.Path, root+"/"):
		key := strings.TrimPrefix(r.URL.Path, root+"/")
		f.handleObject(w, r, key)
	default:
		http.NotFound(w, r)
	}
}

// failNext makes the next count requests to key matching method ("" for any
// method) receive status; count -1 fails until re-armed. Rules for different
// methods on the same key are independent of each other.
func (f *fakeS3) failNext(key, method string, status, count int) {
	f.failNextWithBody(key, method, status, count, nil)
}

// failNextWithBody behaves like failNext but also writes body with the
// status, such as an S3 <Error> document whose Code and Message callers
// surface.
func (f *fakeS3) failNextWithBody(key, method string, status, count int, body []byte) {
	f.mu.Lock()
	defer f.mu.Unlock()
	if f.fails == nil {
		f.fails = make(map[string]*forcedFailure)
	}
	f.fails[method+" "+key] = &forcedFailure{status: status, remaining: count, body: body}
}

// countRequest records one request to key via method, whether or not a
// forced failure matches it, so a test can assert a retrying call's exact
// attempt count through requestCount.
func (f *fakeS3) countRequest(key, method string) {
	f.mu.Lock()
	defer f.mu.Unlock()
	if f.requests == nil {
		f.requests = make(map[string]int)
	}
	f.requests[method+" "+key]++
}

// requestCount reports how many requests key has received via method so
// far, as recorded by countRequest.
func (f *fakeS3) requestCount(key, method string) int {
	f.mu.Lock()
	defer f.mu.Unlock()
	return f.requests[method+" "+key]
}

// shouldFail reports whether key+method matches an armed rule, trying the
// method-specific rule before the wildcard and consuming one use, and returns
// the status and optional body to write. It locks mu; callers must not hold it.
func (f *fakeS3) shouldFail(key, method string) (int, []byte, bool) {
	f.mu.Lock()
	defer f.mu.Unlock()
	for _, k := range [2]string{method + " " + key, " " + key} {
		rule, ok := f.fails[k]
		if !ok || rule.remaining == 0 {
			continue
		}
		if rule.remaining > 0 {
			rule.remaining--
		}
		return rule.status, rule.body, true
	}
	return 0, nil, false
}

// handleBucket answers bucket-level requests: existence probes (HEAD) and
// listing (GET with list-type=2).
func (f *fakeS3) handleBucket(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case http.MethodHead:
		// The bucket always exists in this fake, so ensureBucket's HEAD
		// probe succeeds and it never attempts to create the bucket.
		w.WriteHeader(http.StatusOK)
	case http.MethodGet:
		if r.URL.Query().Get("list-type") == "2" {
			f.handleList(w, r)
			return
		}
		w.WriteHeader(http.StatusOK)
	case http.MethodPost:
		if r.URL.Query().Has("delete") {
			f.handleDeleteObjects(w, r)
			return
		}
		w.WriteHeader(http.StatusMethodNotAllowed)
	default:
		w.WriteHeader(http.StatusMethodNotAllowed)
	}
}

// handleList renders one ListObjectsV2 page of the keys under the requested
// prefix unless a failNext rule on bucketListKey fires first, or defers to
// writeOversizedList if armed; listPage decides the page and its token.
func (f *fakeS3) handleList(w http.ResponseWriter, r *http.Request) {
	f.countRequest(bucketListKey, http.MethodGet)
	if status, body, fail := f.shouldFail(bucketListKey, http.MethodGet); fail {
		w.WriteHeader(status)
		if len(body) > 0 {
			_, _ = w.Write(body)
		}
		return
	}

	f.mu.Lock()
	oversized := f.oversizedList
	omitNext := f.listOmitNextToken
	f.mu.Unlock()
	if oversized {
		f.writeOversizedList(w)
		return
	}

	query := r.URL.Query()
	keys, next, ok := f.listPage(query.Get("prefix"), query.Get("continuation-token"))
	if !ok {
		w.WriteHeader(http.StatusBadRequest)
		return
	}

	var body strings.Builder
	body.WriteString(`<?xml version="1.0" encoding="UTF-8"?>`)
	body.WriteString(`<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">`)
	for _, key := range keys {
		body.WriteString("<Contents><Key>")
		body.WriteString(key)
		body.WriteString("</Key></Contents>")
	}
	if next != "" {
		body.WriteString("<IsTruncated>true</IsTruncated>")
		if !omitNext {
			body.WriteString("<NextContinuationToken>" + next + "</NextContinuationToken>")
		}
	} else {
		body.WriteString("<IsTruncated>false</IsTruncated>")
	}
	body.WriteString("</ListBucketResult>")

	w.Header().Set("Content-Type", "application/xml")
	w.WriteHeader(http.StatusOK)
	_, _ = io.WriteString(w, body.String())
}

// listPage returns the sorted keys under prefix after token's resume point, at
// most listPageSize of them, and a fresh opaque token when more remain; it
// refuses a token it never issued, so a client cannot resume by guessing one.
func (f *fakeS3) listPage(prefix, token string) ([]string, string, bool) {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.listTokensReceived = append(f.listTokensReceived, token)
	after, issued := f.listResume[token]
	if token != "" && !issued {
		return nil, "", false
	}
	keys := make([]string, 0, len(f.objects))
	for key := range f.objects {
		if strings.HasPrefix(key, prefix) && key > after {
			keys = append(keys, key)
		}
	}
	slices.Sort(keys)
	if f.listPageSize == 0 || len(keys) <= f.listPageSize {
		return keys, "", true
	}
	keys = keys[:f.listPageSize]
	next := fmt.Sprintf("opaque-token-%d", len(f.listTokensIssued)+1)
	if f.listResume == nil {
		f.listResume = make(map[string]string)
	}
	f.listResume[next] = keys[len(keys)-1]
	f.listTokensIssued = append(f.listTokensIssued, next)
	return keys, next, true
}

// setListPageSize makes every later listing answer at most size keys per page,
// under mu, since the server is already running when a test arms it.
func (f *fakeS3) setListPageSize(size int) {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.listPageSize = size
}

// setListOmitNextToken makes every later truncated page leave out its
// NextContinuationToken while still reporting IsTruncated true.
func (f *fakeS3) setListOmitNextToken(omit bool) {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.listOmitNextToken = omit
}

// listContinuationTokens returns the tokens listPage issued and the token of
// each request it answered, both in request order.
func (f *fakeS3) listContinuationTokens() ([]string, []string) {
	f.mu.Lock()
	defer f.mu.Unlock()
	return slices.Clone(f.listTokensIssued), slices.Clone(f.listTokensReceived)
}

// writeOversizedList streams a body past helpers.S3ListMaxSize from one
// reused chunk, so the fake never allocates that much; it stops at the first
// write error, which is the client's size-limited reader closing the body.
func (f *fakeS3) writeOversizedList(w http.ResponseWriter) {
	w.Header().Set("Content-Type", "application/xml")
	w.WriteHeader(http.StatusOK)
	chunk := bytes.Repeat([]byte("a"), 64<<10)
	var written int64
	for written <= helpers.S3ListMaxSize {
		n, err := w.Write(chunk)
		written += int64(n)
		if err != nil {
			break
		}
	}
}

// handleDeleteObjects answers a Multi-Object Delete (POST ?delete) unless a
// failNext rule on bucketDeleteObjectsKey fires first. It parses <Delete> with
// encoding/xml, not string matching, so a key with XML metacharacters round-trips.
func (f *fakeS3) handleDeleteObjects(w http.ResponseWriter, r *http.Request) {
	f.countRequest(bucketDeleteObjectsKey, http.MethodPost)
	if status, body, fail := f.shouldFail(bucketDeleteObjectsKey, http.MethodPost); fail {
		w.WriteHeader(status)
		if len(body) > 0 {
			_, _ = w.Write(body)
		}
		return
	}

	body, err := io.ReadAll(r.Body)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	var req deleteRequest
	if err := xml.Unmarshal(body, &req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	f.mu.Lock()
	f.lastDeleteReq = req
	f.lastDeleteHeaders = r.Header.Clone()
	oversized := f.oversizedDeleteResult
	fail := f.failDeleteObjects
	f.mu.Unlock()
	if oversized {
		f.writeOversizedDeleteResult(w)
		return
	}

	var result deleteResult
	f.mu.Lock()
	for _, obj := range req.Objects {
		if fail != nil && obj.Key == fail.key {
			result.Errors = append(result.Errors, deleteError{Key: fail.key, Code: fail.code, Message: fail.message})
			continue
		}
		delete(f.objects, obj.Key)
	}
	f.mu.Unlock()

	payload, err := xml.Marshal(result)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/xml")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(append([]byte(xml.Header), payload...))
}

// writeOversizedDeleteResult streams a body past helpers.S3ListMaxSize like
// writeOversizedList, driving deleteObjectsBatch's size-limited read.
func (f *fakeS3) writeOversizedDeleteResult(w http.ResponseWriter) {
	w.Header().Set("Content-Type", "application/xml")
	w.WriteHeader(http.StatusOK)
	chunk := bytes.Repeat([]byte("a"), 64<<10)
	var written int64
	for written <= helpers.S3ListMaxSize {
		n, err := w.Write(chunk)
		written += int64(n)
		if err != nil {
			break
		}
	}
}

// failDeleteObjectsFor arms handleDeleteObjects to report key as a single
// <Error> entry (with the given code/message) instead of deleting it.
func (f *fakeS3) failDeleteObjectsFor(key, code, message string) {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.failDeleteObjects = &deleteObjectsFailure{key: key, code: code, message: message}
}

// deleteObjectsRequest returns the most recently received Multi-Object
// Delete request body, so a test can assert exactly which <Object> entries
// deleteObjectsBatch sent.
func (f *fakeS3) deleteObjectsRequest() deleteRequest {
	f.mu.Lock()
	defer f.mu.Unlock()
	return f.lastDeleteReq
}

// deleteObjectsHeaders returns the last Multi-Object Delete request's
// headers, so a test can assert Content-MD5, X-Amz-Content-Sha256 and
// Content-Type without the fake verifying SigV4.
func (f *fakeS3) deleteObjectsHeaders() http.Header {
	f.mu.Lock()
	defer f.mu.Unlock()
	return f.lastDeleteHeaders
}

// handleObject answers object-level requests: HEAD, GET, PUT, and DELETE.
func (f *fakeS3) handleObject(w http.ResponseWriter, r *http.Request, key string) {
	switch r.Method {
	case http.MethodHead:
		f.handleHead(w, key)
	case http.MethodGet:
		f.handleGet(w, r, key)
	case http.MethodPut:
		f.handlePut(w, r, key)
	case http.MethodDelete:
		f.handleDelete(w, r, key)
	default:
		w.WriteHeader(http.StatusMethodNotAllowed)
	}
}

// serveSyntheticBody arms key's GET to answer 200 with size generated bytes,
// shadowing any stored object without touching f.objects, so a test can cross
// a large size ceiling without materializing the body anywhere.
func (f *fakeS3) serveSyntheticBody(key string, size int64) {
	f.mu.Lock()
	defer f.mu.Unlock()
	if f.syntheticBodies == nil {
		f.syntheticBodies = make(map[string]int64)
	}
	f.syntheticBodies[key] = size
}

// writeSyntheticBody streams exactly size filler bytes, trimming the last
// chunk, since callers sit one byte on either side of a ceiling; it declares
// no Content-Length and stops at the first write error, a reader giving up.
func writeSyntheticBody(w http.ResponseWriter, contentType string, size int64) {
	w.Header().Set("Content-Type", contentType)
	w.WriteHeader(http.StatusOK)
	const chunkSize = 64 << 10
	chunk := bytes.Repeat([]byte("a"), chunkSize)
	for remaining := size; remaining > 0; {
		next := chunk
		if remaining < chunkSize {
			next = chunk[:remaining]
		}
		n, err := w.Write(next)
		remaining -= int64(n)
		if err != nil {
			break
		}
	}
}

// raceTokenOnNextHead arms a one-shot rewrite of key's stored token on its
// next HEAD, modeling another acquirer's write landing between this call's
// PUT and the ownership-verifying HEAD that claim uses to detect that race.
func (f *fakeS3) raceTokenOnNextHead(key, token string) {
	f.mu.Lock()
	defer f.mu.Unlock()
	if f.headTokenSwaps == nil {
		f.headTokenSwaps = make(map[string]string)
	}
	f.headTokenSwaps[key] = token
}

// storeLockObject writes a lock object (token, deadline, and the ETag that
// reclaimIfExpired requires) straight into the map, bypassing HTTP so a test
// can place a competing write at an exact point without adding a request.
func (f *fakeS3) storeLockObject(key, token string, deadline time.Time) {
	f.mu.Lock()
	defer f.mu.Unlock()
	stored := fakeObject{
		meta: map[string]string{
			"X-Amz-Meta-Token":    token,
			"X-Amz-Meta-Deadline": deadline.UTC().Format(time.RFC3339),
		},
		modified: time.Now(),
	}
	stored.etag = fakeETag(nil, stored.modified, f.nextETagSeq())
	f.objects[key] = stored
}

// dropObject removes an object from the fake's map directly, standing in for a
// holder releasing its lock at an exact point in another acquirer's request
// sequence. It bypasses HTTP for the same reason storeLockObject does.
func (f *fakeS3) dropObject(key string) {
	f.mu.Lock()
	defer f.mu.Unlock()
	delete(f.objects, key)
}

// handleHead reports the stored object's metadata headers and Last-Modified,
// or 404 if absent; a failNext rule wins first, and a raceTokenOnNextHead
// swap is applied to the stored object before the response is built.
func (f *fakeS3) handleHead(w http.ResponseWriter, key string) {
	f.countRequest(key, http.MethodHead)
	// An armed body is not written: a HEAD response carries no entity body.
	if status, _, fail := f.shouldFail(key, http.MethodHead); fail {
		w.WriteHeader(status)
		return
	}
	f.mu.Lock()
	obj, ok := f.objects[key]
	if ok {
		if token, swap := f.headTokenSwaps[key]; swap {
			// Clone rather than write through the stored map: every
			// write publishes a fresh meta map, because handleHead and
			// handleGet read obj.meta after releasing f.mu.
			fresh := maps.Clone(obj.meta)
			fresh["X-Amz-Meta-Token"] = token
			obj.meta = fresh
			f.objects[key] = obj
			delete(f.headTokenSwaps, key)
		}
	}
	withETag := !f.suppressETag
	f.mu.Unlock()
	if !ok {
		w.WriteHeader(http.StatusNotFound)
		return
	}
	writeObjectHeaders(w.Header(), obj, withETag)
	w.WriteHeader(http.StatusOK)
}

// handleGet returns the stored object's metadata headers and body, or 404 if
// absent; a failNext rule wins first, a serveSyntheticBody size shadows the
// stored object, and a dripGet drip replaces the normal body.
func (f *fakeS3) handleGet(w http.ResponseWriter, r *http.Request, key string) {
	f.countRequest(key, http.MethodGet)
	if status, body, fail := f.shouldFail(key, http.MethodGet); fail {
		w.WriteHeader(status)
		if len(body) > 0 {
			_, _ = w.Write(body)
		}
		return
	}
	f.mu.Lock()
	syntheticSize, synthetic := f.syntheticBodies[key]
	obj, ok := f.objects[key]
	interval, dripping := f.drips[key]
	withETag := !f.suppressETag
	f.mu.Unlock()
	if synthetic {
		writeSyntheticBody(w, "application/json", syntheticSize)
		return
	}
	if !ok {
		w.WriteHeader(http.StatusNotFound)
		return
	}
	writeObjectHeaders(w.Header(), obj, withETag)
	w.WriteHeader(http.StatusOK)
	if dripping {
		driveDripGet(w, r, interval)
		return
	}
	_, _ = w.Write(obj.data)
}

// dripGet makes every GET of key send the real headers and 200, then a body
// that never completes (see driveDripGet): an endpoint that keeps making
// glacial progress and so never trips a read-inactivity watchdog.
func (f *fakeS3) dripGet(key string, interval time.Duration) {
	f.mu.Lock()
	defer f.mu.Unlock()
	if f.drips == nil {
		f.drips = make(map[string]time.Duration)
	}
	f.drips[key] = interval
}

// driveDripGet writes one flushed filler byte per interval until r's context
// is done, like fakegalaxy's DripInterval; with no Content-Length the response
// is chunked, so a client cannot infer completion from a declared length.
func driveDripGet(w http.ResponseWriter, r *http.Request, interval time.Duration) {
	flusher, _ := w.(http.Flusher)
	for {
		if _, err := w.Write([]byte{' '}); err != nil {
			return
		}
		if flusher != nil {
			flusher.Flush()
		}
		select {
		case <-r.Context().Done():
			return
		case <-time.After(interval):
		}
	}
}

// nextETagSeq returns the next version number for a stored object. The caller
// already holds mu, which is where every write to the object map happens.
func (f *fakeS3) nextETagSeq() uint64 {
	f.etagSeq++
	return f.etagSeq
}

// handlePut stores the body and X-Amz-Meta-* headers under key unless a failNext
// rule fires first, honoring the lock's conditional headers. If-Match on an absent
// key answers 404, not 412, as S3 does; reclaimIfExpired reads that as a release.
func (f *fakeS3) handlePut(w http.ResponseWriter, r *http.Request, key string) {
	f.countRequest(key, http.MethodPut)
	body, err := io.ReadAll(r.Body)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if status, failBody, fail := f.shouldFail(key, http.MethodPut); fail {
		w.WriteHeader(status)
		if len(failBody) > 0 {
			_, _ = w.Write(failBody)
		}
		return
	}

	f.mu.Lock()
	defer f.mu.Unlock()
	if status, refused := f.conditionalRefusal(r, key); refused {
		w.WriteHeader(status)
		return
	}
	stored := fakeObject{
		data:     body,
		meta:     captureMeta(r.Header),
		modified: time.Now(),
	}
	stored.etag = fakeETag(body, stored.modified, f.nextETagSeq())
	f.objects[key] = stored
	w.Header().Set("ETag", stored.etag)
	w.WriteHeader(http.StatusOK)
}

// conditionalRefusal evaluates a PUT's If-None-Match and If-Match against
// what is stored, reporting the status to answer and whether the write is
// refused. The caller already holds mu.
func (f *fakeS3) conditionalRefusal(r *http.Request, key string) (int, bool) {
	if !f.ignoreIfNoneMatch && r.Header.Get("If-None-Match") == "*" {
		if _, exists := f.objects[key]; exists {
			return http.StatusPreconditionFailed, true
		}
	}
	want := r.Header.Get("If-Match")
	if want == "" || f.ignoreIfMatch {
		return 0, false
	}
	current, exists := f.objects[key]
	switch {
	case f.refuseIfMatch, exists && current.etag != want:
		return http.StatusPreconditionFailed, true
	case !exists:
		return http.StatusNotFound, true
	}
	return 0, false
}

// captureMeta extracts the X-Amz-Meta-* headers from an incoming request,
// keyed by their canonical header name, so handleHead/handleGet can echo
// them back verbatim on later reads.
func captureMeta(header http.Header) map[string]string {
	meta := make(map[string]string, len(header))
	for name, values := range header {
		if len(values) == 0 || !strings.HasPrefix(strings.ToLower(name), "x-amz-meta-") {
			continue
		}
		meta[name] = values[0]
	}
	return meta
}

// writeObjectHeaders sets obj's captured metadata, Last-Modified and, when
// withETag, the ETag; the caller samples withETag under mu, since this runs
// after f.mu is released and reading f.suppressETag here would race.
func writeObjectHeaders(header http.Header, obj fakeObject, withETag bool) {
	for name, value := range obj.meta {
		header.Set(name, value)
	}
	header.Set("Last-Modified", obj.modified.UTC().Format(http.TimeFormat))
	if obj.etag != "" && withETag {
		header.Set("ETag", obj.etag)
	}
}

// setSuppressETag arms (or disarms) the ETag-withholding shape mid-run, under
// mu, so a fixture can let Open's own probe pass and only then take the
// guarantee away.
func (f *fakeS3) setSuppressETag(suppress bool) {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.suppressETag = suppress
}

// handleDelete removes the object, reporting success even when it is absent
// as S3 does; a failNext rule wins first, and deleteDelay stalls it until the
// delay or the request's context ends, so a test can drive a DELETE timeout.
func (f *fakeS3) handleDelete(w http.ResponseWriter, r *http.Request, key string) {
	f.countRequest(key, http.MethodDelete)
	if status, body, fail := f.shouldFail(key, http.MethodDelete); fail {
		w.WriteHeader(status)
		if len(body) > 0 {
			_, _ = w.Write(body)
		}
		return
	}
	f.mu.Lock()
	delay := f.deleteDelay
	f.mu.Unlock()
	if delay > 0 {
		timer := time.NewTimer(delay)
		defer timer.Stop()
		select {
		case <-r.Context().Done():
			http.Error(w, r.Context().Err().Error(), http.StatusGatewayTimeout)
			return
		case <-timer.C:
		}
	}

	f.mu.Lock()
	delete(f.objects, key)
	f.mu.Unlock()
	w.WriteHeader(http.StatusNoContent)
}

// newTestBackend starts a fake S3 server and returns a Backend configured
// to talk to it in path-style mode. SigV4 signatures are computed by the
// real client but never verified by the fake.
func newTestBackend(t *testing.T) *Backend {
	t.Helper()
	return newTestBackendWithFake(t, newFakeS3())
}

// newTestBackendAndFake behaves like newTestBackend but also returns the
// *fakeS3 backing it, so a test can arm fault injection via failNext or
// failNextWithBody against the same server the returned Backend talks to.
func newTestBackendAndFake(t *testing.T) (*Backend, *fakeS3) {
	t.Helper()
	fake := newFakeS3()
	return newTestBackendWithFake(t, fake), fake
}

// newNonConformingTestBackend starts a fake S3 server with
// ignoreIfNoneMatch set, simulating a backend that does not enforce
// conditional PUT, and returns a Backend pointed at it.
func newNonConformingTestBackend(t *testing.T) *Backend {
	t.Helper()
	fake := newFakeS3()
	fake.ignoreIfNoneMatch = true
	return newTestBackendWithFake(t, fake)
}

// newTestBackendWithFake starts fake as an httptest server and returns a
// Backend configured to talk to it in path-style mode. SigV4 signatures are
// computed by the real client but never verified by the fake.
func newTestBackendWithFake(t *testing.T, fake *fakeS3) *Backend {
	t.Helper()

	srv := httptest.NewServer(fake)
	t.Cleanup(srv.Close)

	cfg := config.S3CacheConfig{
		Endpoint:  srv.URL,
		Bucket:    fake.bucket,
		Region:    "us-east-1",
		AccessKey: "x",
		SecretKey: config.NewSecret("y"),
		PathStyle: true,
		Enabled:   true,
	}
	backend, err := New(cfg, srv.Client(), t.TempDir())
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	return backend
}

// newAcceptingNeverRespondingListener starts a local TCP listener that
// accepts and drains every connection but never responds, so a caller hits
// its response-header timeout; the counter counts accepted connections.
func newAcceptingNeverRespondingListener(t *testing.T) (net.Listener, *atomic.Int32) {
	t.Helper()
	var lc net.ListenConfig
	ln, err := lc.Listen(context.Background(), "tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("net.Listen: %v", err)
	}
	// done holds accepted connections open until cleanup: closing one right
	// after draining would turn the intended timeout into an EOF or reset.
	done := make(chan struct{})
	t.Cleanup(func() {
		close(done)
		_ = ln.Close()
	})

	var accepted atomic.Int32
	go func() {
		for {
			conn, err := ln.Accept()
			if err != nil {
				return
			}
			accepted.Add(1)
			go func(c net.Conn) {
				buf := make([]byte, 4096)
				_, _ = c.Read(buf) // drain the request; a response is never written.
				<-done             // hold the connection open, silently, until the test cleans up.
				_ = c.Close()
			}(conn)
		}
	}()

	return ln, &accepted
}
